######################################################################
# Automatically generated by qmake (2.01a) jue oct 24 22:44:47 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h masterthread.h
SOURCES += dialog.cpp main.cpp masterthread.cpp
CONFIG  += serialport
